import json
from pathlib import Path
D=[]
def add(title,focus,l,lq,r,rq,words):
    D.append(dict(day=len(D)+1,title=title,focus=focus,listening=dict(text=l,questions=lq),reading=dict(text=r,questions=rq),words=words))
def q(prompt,a,b,c,answer,why):
    return dict(prompt=prompt,options=[a,b,c],answer=answer,why=why)

add('予定の変更','数字・訂正：最初の情報と最終決定を区別する',
"Hi, this is Maya from the training team. Our workshop was originally planned for Wednesday morning, but the trainer's flight has been delayed. We've moved it to Thursday at two in the afternoon. The room is still the same, on the third floor. You don't need to register again. However, if the new time doesn't work for you, please email me by Tuesday evening. We'll send a recording to anyone who can't attend, although the question session won't be included.",
[q('When will the workshop take place?','Wednesday morning','Thursday afternoon','Tuesday evening',1,'moved it to Thursday at two が最終決定。Wednesday は変更前、Tuesday は連絡期限。'),q('What will people who miss the workshop receive?','A recording without the question session','A new registration form','A recording of only the questions',0,'a recording … although the question session won’t be included。質問部分は含まれない。')],
"From next month, the town library will open at nine instead of ten on weekdays. Closing times will remain unchanged. The earlier opening is a three-month trial requested by students who want to study before classes. During the trial, visitors can use the study area and borrow books, but the information desk will not open until ten. Staff will count morning visitors before deciding whether to keep the new hours. Weekend opening times will stay the same.",
[q('What is the main purpose of the notice?','To announce permanent weekend hours','To explain an earlier-opening trial','To recruit library staff',1,'three-month trial と、期間中のサービス・判断方法を説明している。永続的変更ではない。'),q('What can a visitor do at 9:30 on a weekday during the trial?','Ask the information desk for help','Attend a class run by staff','Borrow a book',2,'borrow books は可能。information desk は10時まで開かない。')],
['originally＝当初は','remain unchanged＝変わらない','trial＝試行'])

add('勧める理由','主旨：例よりも結論をつかむ',
"I used to drive to the office because I thought the bus would take much longer. Last month, my car needed repairs, so I tried the express bus. The journey was only ten minutes longer, and I could read instead of watching traffic. I still drive when I need to collect my daughter early, but most days I take the bus now. It isn't always perfectly on time. Still, arriving a little later feels better than starting the day already tired from driving.",
[q('Why does the speaker usually take the bus now?','It makes the journey less tiring','It is always faster','Parking has become impossible',0,'read instead of watching traffic と最後の tired from driving が理由。所要時間は長い。'),q('When does the speaker still drive?','Whenever the bus is late','Every Monday','When an early pickup is needed',2,'when I need to collect my daughter early が条件。')],
"A small company introduced a quiet hour after lunch. During this time, employees avoid internal meetings and turn off non-urgent notifications. Customers can still contact the support team as usual. The company did not introduce the rule to make people work faster. Instead, it wanted to give everyone a predictable period for tasks requiring concentration. Some employees prefer to concentrate in the morning, so managers allow teams to choose a different hour if all members agree.",
[q('Why was the quiet hour introduced?','To reduce customer enquiries','To provide reliable time for focused work','To shorten the working day',1,'predictable period … requiring concentration が主目的。faster は明確に否定。'),q('How can a team change its quiet hour?','By getting agreement from every member','By asking customers','By cancelling all meetings permanently',0,'if all members agree。全員の同意が条件。')],
['collect＝迎えに行く','predictable＝予測できる・予定が立つ','concentration＝集中'])

add('同じ意味を探す','言い換え：本文と選択肢の語が違っても照合する',
"The cooking class was more practical than I expected. We didn't spend the evening watching the chef. After a short demonstration, we worked in pairs and made a complete meal ourselves. I was worried about having to buy unusual ingredients afterwards, but everything we used was available in an ordinary supermarket. The class wasn't cheap, though. I'd recommend it to someone who wants confidence in the kitchen, rather than someone who just wants an inexpensive night out with friends.",
[q('What did participants mainly do?','Watch a long demonstration','Prepare food themselves','Shop for ingredients',1,'worked in pairs and made … ourselves を prepare food themselves と言い換える。'),q('Who would benefit most, according to the speaker?','Someone seeking the cheapest evening out','Someone wanting rare ingredients','Someone wanting to feel more confident cooking',2,'wants confidence in the kitchen。値段の安さは勧める理由ではない。')],
"Visitors to the new art space do not need to book tickets for the main exhibition. However, workshops have limited places and must be reserved online. The space encourages visitors to take photographs for personal use, provided they turn off the flash. Large bags must be left in the free lockers near the entrance. Although entry is free, donations help pay for school visits. The organisers hope that removing the ticket price will make local residents feel more comfortable dropping in regularly.",
[q('Which activity requires an advance reservation?','Seeing the main exhibition','Taking photographs','Joining a workshop',2,'workshops … must be reserved online。book と reserve はここでは同義。'),q('Why is entry free?','To encourage frequent informal visits','To stop school visits','To attract only professional artists',0,'dropping in regularly＝気軽に繰り返し訪れる。')],
['practical＝実践的な','provided＝〜という条件で','drop in＝気軽に立ち寄る'])

add('理由と結果','because / so / rather than のつながりを追う',
"We received several complaints about deliveries arriving late, so we checked the last month's orders. At first, we suspected the new delivery company. In fact, most parcels had left our warehouse a day later than planned because our address-checking software kept stopping. The delivery company usually completed its part on time. We're fixing the software this week. Until then, an extra member of staff will check addresses manually. Changing delivery companies wouldn't solve the problem we've actually found.",
[q('What caused most of the delays?','The delivery company lost parcels','Orders left the warehouse late','Customers changed their addresses',1,'software kept stopping により warehouse 出発が遅れた。最初の疑いと調査結果を区別。'),q('What is the temporary solution?','Use another delivery company','Stop taking orders','Have someone check addresses manually',2,'Until then … check addresses manually が修理完了までの対応。')],
"The community garden has replaced its weekly watering schedule with a weather-based system. Previously, volunteers watered every Saturday, even after heavy rain. The new system asks them to check the soil before adding water. This should reduce waste and protect plants from getting too much water. It does not mean volunteers can stop visiting during rainy weeks: they still need to inspect the plants and remove weeds. The garden coordinator will review water use at the end of the summer.",
[q('What is the expected benefit of the new system?','Less unnecessary watering','Fewer types of plants','No need for volunteers',0,'reduce waste と too much water を避けることが利点。'),q('What must volunteers still do in rainy weeks?','Water every plant','Inspect plants and remove weeds','Close the garden',1,'does not mean … stop visiting の後に残る仕事が明記されている。')],
['suspect＝疑う','manually＝手作業で','soil＝土壌'])

add('例外を見落とさない','unless / except / only に印をつける',
"Your gym membership lets you attend most classes without paying extra. The exception is the small-group swimming course, which has a separate fee because places are limited to four people. You can cancel a class booking free of charge until six hours before it starts. After that, a fee applies unless the instructor cancels the class. Please note that simply failing to arrive counts as a late cancellation. If you are unsure you'll make it, remove your booking early so another member can use the place.",
[q('Which class costs extra?','All evening classes','The small-group swimming course','Every class with an instructor',1,'The exception … separate fee が追加料金の対象。'),q('When is a late cancellation free?','When the instructor cancels','When the member forgets','When the member arrives late',0,'unless the instructor cancels は料金の例外条件。')],
"Employees may borrow a company laptop for personal study at weekends, as long as it is returned before nine on Monday morning. Devices containing confidential client files are excluded from this scheme. Anyone borrowing a laptop must record its number in the equipment register and report damage immediately. Software cannot be installed without permission from the IT team. The scheme is intended to support learning; it does not give employees permission to use company devices for paid work for other organisations.",
[q('Which laptop may NOT be borrowed under the scheme?','One returned on Sunday','One used for language study','One holding confidential client files',2,'Devices containing confidential client files are excluded。'),q('What is required before installing software?','Payment to another organisation','Permission from IT','A Monday morning meeting',1,'cannot be installed without permission。二重の否定に注意。')],
['exception＝例外','unless＝〜でない限り','be excluded＝対象外である'])

add('言葉の裏の意図','依頼・遠回しな不満を根拠から読む',
"Thanks for sending the draft so quickly. The examples are clear, and I like the shorter introduction. I'm less sure about the final section, though. We promise that customers will save money immediately, but we only have results from a small trial. Could we make that claim a little more cautious? I don't think we need to start again. If you revise those last two paragraphs today, I can check them tomorrow morning and we should still meet Friday's deadline.",
[q('What does the speaker want changed?','The whole report','The introduction','The strength of the final claim',2,'make that claim a little more cautious。全面改稿は不要と言っている。'),q('How does the speaker view the deadline?','It can probably still be met','It must be moved to next month','It has already been missed',0,'should still meet Friday’s deadline は見込み。確実という断言ではない。')],
"A customer wrote: 'The hotel room was clean and the staff were welcoming. However, the website describes the building as a short walk from the station. It took us twenty-five minutes with our bags, mostly uphill. We would have booked a taxi if we had known. Please give a distance or an approximate walking time on the website. This would help future guests plan their arrival more realistically.' The customer did not request a refund or question the quality of the room.",
[q('What is the customer mainly asking the hotel to do?','Refund the room charge','Describe its location more precisely','Move closer to the station',1,'give a distance or an approximate walking time が依頼。'),q('Why does the customer mention the bags and hill?','To explain why the walk was harder than expected','To praise the exercise facilities','To show that the station was closed',0,'short walk という説明と実際の負担の差を具体化している。')],
['cautious＝慎重な','claim＝主張','approximately＝およそ'])

add('第1週チェック','初見で解き、間違いを「数字・言い換え・条件・推論」に分類する',
"A quick update about Saturday's volunteering event. The river path is too wet to work on safely, so we'll clean the playground instead. Meet at the school gate at the usual time, nine thirty. You don't need to bring tools, but please bring your own lunch. We'll finish by one unless heavy rain forces us to stop earlier. People who signed up only for the river project can withdraw; just let us know by Friday so we can organise the teams.",
[q('What has changed?','The meeting time','The work location','The need to register',1,'river path から playground に変更。集合時刻は usual time。'),q('What should someone who no longer wants to join do?','Notify the organisers by Friday','Bring tools on Saturday','Wait at the river',0,'withdraw … let us know by Friday が辞退の手続き。')],
"The museum is testing an evening opening once a month. Its director hopes to attract people whose working hours prevent daytime visits. During the first evening, ticket sales were lower than expected, but visitors stayed longer and many joined a guided tour. The director says one evening is not enough to judge demand. The trial will continue for five more months, after which the museum will compare staffing costs with income and visitor feedback before deciding whether to extend it.",
[q('Why does the director want to continue the trial?','The first evening proved it profitable','Staff costs have disappeared','More evidence is needed',2,'one evening is not enough to judge demand。初回だけで判断しない。'),q('Who is the trial mainly intended to reach?','People unable to visit during the day because of work','Only school groups','Visitors who dislike guided tours',0,'working hours prevent daytime visits を言い換えた選択肢。')],
['withdraw＝参加を取りやめる','judge demand＝需要を判断する','feedback＝意見・反応'])

add('比較を正確に読む','安い・速い・便利を混同しない',
"I've compared the two venues for our team event. The central hotel charges less for the room, but we'd have to pay separately for lunch and the projector. The conference centre includes both, so its total price is slightly lower. Getting there takes longer for most of us, though. My suggestion is to choose the centre and start half an hour later. That would keep us within budget without making people leave home earlier. We should confirm whether the later start is available before booking.",
[q('Why does the speaker prefer the conference centre?','Its total cost is lower','It is closer to everyone','Its room-only price is lower',0,'昼食・機材を含めた total price で比較している。部屋代だけではホテルが安い。'),q('What still needs checking?','Whether lunch can be removed','Whether they can start later','Whether the hotel has rooms',1,'confirm whether the later start is available before booking。')],
"Two online courses teach the same basic photography skills. Course A provides recorded lessons that learners can watch whenever they like. Course B has live evening sessions and costs more, but includes personal feedback on three assignments. Neither course requires an expensive camera. For learners with unpredictable schedules, flexibility may matter more than feedback. Those who find it difficult to study alone may prefer regular live sessions. The best choice therefore depends on how a learner studies, rather than simply on the number of lessons.",
[q('Who would probably prefer Course A?','Someone requiring personal feedback','Someone with an unpredictable timetable','Someone needing fixed live sessions',1,'録画を好きな時に見られるので、不規則な予定に合う。'),q('What is the writer’s main conclusion?','The cheaper course is always better','An expensive camera is essential','Study habits should guide the choice',2,'depends on how a learner studies が結論。')],
['within budget＝予算内で','assignment＝課題','flexibility＝柔軟性'])

add('態度をつかむ','肯定の後の but / though に注目する',
"The new booking app is certainly easier to navigate. I found the right appointment in seconds, and the confirmation arrived immediately. What bothers me is that it asks for access to my contacts before I can finish booking. I can't see why a haircut requires that information. I'd happily keep using the app if that step became optional. Until then, I'll probably phone the salon, even though it takes longer. Convenience is useful, but it isn't my only consideration.",
[q('What is the speaker’s attitude towards the app?','Completely satisfied','Unconcerned about personal information','Positive about usability but concerned about access to data',2,'操作性は評価しつつ contacts へのアクセスに不満。'),q('What change would encourage continued use?','Making contact access optional','Adding more appointment reminders','Requiring faster bookings',0,'if that step became optional が継続利用の条件。')],
"The town's cycle-lane plan has received a cautious welcome from local shop owners. Many support making the street safer, but they worry that removing short-stay parking could discourage customers collecting heavy purchases. The council has suggested adding loading bays on nearby streets. Shop owners say the idea could help, provided the bays are close enough and rules are clearly displayed. They have asked to see the detailed design before supporting the final proposal. Their response is conditional, rather than a rejection of cycling improvements.",
[q('How do shop owners view the plan?','They support every detail already','They are open to it but have conditions','They reject any cycling improvements',1,'cautious welcome と conditional が態度。全面支持でも全面拒否でもない。'),q('What does “the idea” refer to?','Removing all shops','Increasing heavy purchases','Adding nearby loading bays',2,'直前の council has suggested adding loading bays を指す。')],
['optional＝任意の','consideration＝考慮すること','conditional＝条件付きの'])

add('指示語を追う','this / they / it が何を指すか確かめる',
"We tried sending all customer questions to one shared inbox. This made it easier to see what had arrived, but it created another problem: several people sometimes answered the same message. To prevent that, we've added a simple rule. Whoever starts handling a question puts their name beside it. They don't have to solve it immediately, but they become responsible for keeping the customer updated. We'll review the system next week; there's no need to buy new software unless this change fails to help.",
[q('What problem did the shared inbox create?','Some questions received multiple replies','Nobody could see new messages','Customers had to buy software',0,'several people … answered the same message が重複返信。'),q('What must the named person do?','Solve every question immediately','Keep the customer informed','Review software prices today',1,'responsible for keeping the customer updated。即解決は必須ではない。')],
"A school began lending musical instruments to beginners. The instruments are donated by local residents and checked by a repair specialist before use. This makes lessons accessible to families who cannot afford to buy one immediately. Students can keep an instrument for one term, then renew the loan if nobody else is waiting. The school also offers maintenance sessions. These teach students how to care for borrowed equipment, reducing damage and helping the instruments remain available for future learners.",
[q('What does “These” in the final sentence refer to?','Local residents','Maintenance sessions','Future learners',1,'直前の maintenance sessions が、手入れの仕方を教える。'),q('When may a student renew a loan?','Whenever they pay for repairs','Only after buying an instrument','When there is no waiting borrower',2,'if nobody else is waiting が延長条件。')],
['responsible for＝〜に責任がある','renew＝更新する','maintenance＝手入れ・保守'])

add('事実と推測','分かったことと、まだ分からないことを分ける',
"Sales increased after we changed the product packaging, which is encouraging. But I wouldn't attribute the entire rise to the new design. We also reduced the price that month, and a popular blogger mentioned the product. Customers in our survey liked the clearer label, yet that doesn't tell us why they bought it. Before spending money on redesigning the whole range, I'd test the new packaging on one more product while keeping its price unchanged. That should give us a clearer comparison.",
[q('Why is the speaker cautious about the sales increase?','The survey showed everyone disliked the label','Other changes may have contributed','No products were sold',1,'値下げと blogger の紹介もあり、包装だけの効果と断定できない。'),q('What does the speaker propose?','Redesign the whole range immediately','Stop surveying customers','Test another product without changing its price',2,'one more product while keeping its price unchanged が次の検証。')],
"A workplace survey found that employees who used the office garden reported lower stress than those who did not. The company described the result as promising, but the survey did not show that the garden caused the difference. People with lighter workloads may have had more time to visit it. The company will keep the garden open and invite more employees to use it. It also plans to ask about workload in the next survey, so that the results can be interpreted more carefully.",
[q('What can be concluded from the survey?','Garden users reported less stress','The garden definitely reduced everyone’s stress','Garden users worked longer hours',0,'reported lower stress は観察事実。因果関係は本文で否定されている。'),q('Why will the next survey ask about workload?','To close the garden','To examine another possible explanation','To stop employees taking breaks',1,'lighter workloads が別の説明となり得るため。')],
['attribute A to B＝AをBの結果と考える','contribute＝一因となる','interpret＝解釈する'])

add('条件付きの決定','決定済み・提案中・条件付きの違いを読む',
"We can offer you the flat from the first of June, provided your references arrive by next Wednesday. The landlord has agreed to repaint the bedroom, but replacing the kitchen cupboards hasn't been approved. If you want that work done before moving in, the start date may need to change. My advice is to secure the flat first and discuss the cupboards later. I can send you the draft agreement today, though please don't treat it as confirmation until we've checked the references.",
[q('What must happen before the offer is confirmed?','The cupboards must be replaced','The references must be checked','The tenant must repaint the room',1,'don’t treat it as confirmation until … checked the references。'),q('Which improvement has already been agreed?','Repainting the bedroom','Replacing all kitchen cupboards','Changing the moving date',0,'has agreed to repaint と hasn’t been approved を対比。')],
"The university will run a weekend writing workshop if at least twelve students register by Friday. Places are limited to twenty, and priority will go to students preparing their final projects. Other students may join if spaces remain after the deadline. Registration is an expression of interest; payment will only be requested once the workshop is confirmed. Anyone who needs wheelchair access should mention this on the form so that an appropriate room can be arranged. The venue has not yet been selected.",
[q('What determines whether the workshop will run?','All places being sold','Payment before registration','At least twelve registrations by Friday',2,'if at least twelve … by Friday が開催条件。定員20とは別。'),q('Why should access requirements be stated on the form?','To help select a suitable room','To receive automatic priority','To avoid paying the fee',0,'so that an appropriate room can be arranged が目的。')],
['provided＝〜ならば','reference＝推薦・照会情報','expression of interest＝参加意向の表明'])

add('文脈の語彙','知らない語を前後の具体例から推測する',
"The project needs a more realistic schedule. At the moment, there's no buffer between finishing the interviews and presenting the findings. If even one participant changes their appointment, we'll be rushing the analysis. I'm not suggesting that we move the presentation yet. We could start the interviews two days earlier instead, giving ourselves some room for unexpected delays. That would require confirming participants this week. It's a small adjustment now that could prevent a much bigger problem near the deadline.",
[q('What does “buffer” mean in this context?','A presentation device','Extra time for possible delays','A list of participants',1,'遅延すると分析を急ぐ説明、room for unexpected delays から時間の余裕と分かる。'),q('What change is suggested?','Starting interviews earlier','Cancelling the analysis','Moving the presentation immediately',0,'start the interviews two days earlier。発表延期はまだ提案していない。')],
"The café's new menu is deliberately modest: it offers six main dishes rather than the previous twenty. This streamlined approach allows the kitchen to buy fewer ingredients and prepare them more consistently. Some regular customers miss the wider choice, but the owner says food waste has fallen. She is not ruling out adding dishes in future. For now, however, she wants the team to master the shorter menu before expanding it. She sees the change as a way to improve reliability, not simply to reduce spending.",
[q('What does “streamlined” most nearly mean here?','Made more complicated','Made cheaper by using poor ingredients','Simplified to work efficiently',2,'20から6品へ絞り、材料と調理を安定させる文脈。'),q('What is the owner’s current priority?','Restoring all twenty dishes','Preparing the smaller menu consistently well','Opening another café',1,'master the shorter menu before expanding it と reliability が根拠。')],
['buffer＝余裕・緩衝','streamlined＝無駄を省いた','rule out＝可能性を除外する'])

add('第2週チェック','比較・指示語・条件・因果を組み合わせる',
"The pilot mentoring scheme received good feedback, but only half the pairs met as often as planned. Several mentors said the monthly reporting form took too long. We could shorten it, although we still need enough information to spot problems. I suggest testing a three-question form next month before extending the scheme to other departments. The positive comments are worth taking seriously, but we also need to know whether people can maintain the arrangement when their normal workload increases.",
[q('What is proposed for next month?','Expanding to every department','Ending all reporting','Testing a shorter reporting form',2,'three-question form … before extending が順序。'),q('What concern remains?','Whether participation can continue during busy periods','Whether everyone disliked mentoring','Whether the forms need more questions',0,'maintain … when … workload increases が継続性への懸念。')],
"The sports centre compared two ways of encouraging attendance. One group received weekly reminder messages; another received a discount for attending four times in a month. Attendance rose in both groups, but the discount group started with more frequent visitors. This makes a direct comparison difficult. The manager will repeat the trial with groups that have similar attendance histories. She also wants to check whether any improvement lasts after reminders or discounts stop, rather than judging success only during the trial.",
[q('Why is the first comparison difficult to interpret?','Both groups had identical histories','The groups differed before the trial','Nobody received reminders',1,'discount group started with more frequent visitors。出発点が異なる。'),q('What additional outcome will the manager investigate?','Whether gains continue after support ends','Which message is longest','Whether all visitors want a discount',0,'lasts after reminders or discounts stop が追加の確認点。')],
['maintain＝維持する','attendance＝出席・利用','last＝続く'])

add('譲歩と結論','although で認めた点と、最終主張を分ける',
"I understand why people want every team meeting recorded. It's useful for colleagues in other time zones. On the other hand, some of our best discussions happen when people are willing to suggest unfinished ideas, and recording can make them more cautious. Rather than recording everything, I'd share a written summary of decisions and record only formal presentations. We could still arrange a short follow-up call for anyone who needs context. Access matters, but so does creating space for honest discussion.",
[q('What is the speaker’s preferred approach?','Record every discussion','Share decision summaries and record presentations','Stop supporting remote colleagues',1,'Rather than … 以下に代案がある。'),q('Why might recording affect discussions?','People may hesitate to share undeveloped ideas','It always makes meetings longer','Remote colleagues cannot use recordings',0,'unfinished ideas を出す時に more cautious になると説明。')],
"Although digital tickets reduce paper use, they can create difficulties for visitors whose phones run out of battery. A theatre therefore continues to provide printed tickets on request. Its manager argues that sustainability should be pursued without making access unnecessarily difficult. Staff encourage digital tickets during booking but do not charge for paper copies. The theatre is also reviewing energy use, which the manager believes deserves at least as much attention as ticket materials. She regards paper reduction as one useful measure within a broader effort.",
[q('What is the manager’s position?','Environmental goals should be balanced with accessibility','Printed tickets should be banned immediately','Ticket paper is the only environmental issue',0,'sustainability … without making access … difficult が中心。'),q('Why is energy use mentioned?','To justify charging for paper','To show digital tickets use no energy','To illustrate the wider environmental effort',2,'broader effort の一例で、紙以外も検討している。')],
['unfinished＝未完成の','on request＝希望すれば','pursue＝追求する'])

add('提案の目的','何をするかに加え、なぜするかを答える',
"Before we order new desks, I'd like us to borrow a few adjustable ones for a month. They look useful, but the staff who tried them at the exhibition only used them for a few minutes. A longer trial would show whether people actually change position during a normal working day. We should include colleagues with different roles, not just those who already want a standing desk. Otherwise, we may get enthusiastic feedback that doesn't represent the whole office. Purchasing can wait until we have that information.",
[q('What is the main purpose of the proposed trial?','To decorate the exhibition','To see how desks are used in normal work','To delay all office improvements indefinitely',1,'normal working day の実際の使い方を確認したい。'),q('Why involve people with different roles?','To obtain more representative feedback','To make the trial shorter','To avoid collecting opinions',0,'doesn’t represent the whole office を避けるため。')],
"A neighbourhood group has placed temporary benches along a busy walking route. Instead of choosing permanent locations immediately, it will observe where people stop and ask users about comfort and safety. One bench is near a crossing, where older residents often pause. Another is beside a shop, but the owner worries it may obstruct deliveries. The group says the trial is intended to identify such conflicts early. Benches that prove useful can remain, while others can be moved before money is spent on permanent installation.",
[q('Why are the benches temporary?','The group wants to stop walking','No one is allowed to sit yet','Their usefulness and placement need testing',2,'observe where people stop、conflicts early、moved before … permanent が理由。'),q('What concern is raised about one location?','It is too far from all shops','It could interfere with deliveries','Older residents never use it',1,'obstruct deliveries＝配送を妨げる。')],
['representative＝全体を代表する','obstruct＝妨げる','installation＝設置'])

add('論点の変化','以前の考え→新しい情報→今の立場を追う',
"At first I thought the repair service was too expensive. A new kettle costs only a little more, after all. Then the technician explained that the fee includes checking the cable, replacing the damaged switch, and a six-month guarantee. That changed my view, especially because I like the kettle I already own. I still wouldn't repair every cheap appliance, but in this case the price seems reasonable. Next time, I'll ask what's included before comparing repair costs with the price of a replacement.",
[q('What changed the speaker’s opinion?','A reduction in the repair price','Learning what the repair fee covers','Being offered a free new kettle',1,'説明を聞いて That changed my view。値下げではない。'),q('What will the speaker do differently next time?','Ask about the scope of the service first','Always replace every appliance','Avoid comparing prices',0,'ask what’s included before comparing が今後の行動。')],
"An editor originally opposed publishing reader comments because she expected moderation to require too much staff time. After a limited trial, she found that clear rules and a delay before comments appeared kept the workload manageable. She now supports comments on selected articles. However, she does not favour opening every article to discussion, since some sensitive topics require closer supervision. Her position has shifted from general opposition to selective support, based on the trial rather than a belief that moderation is no longer necessary.",
[q('How has the editor’s position changed?','From support to complete opposition','From opposition to conditional support','From caution to removing all rules',1,'general opposition to selective support と明記されている。'),q('What helped keep moderation manageable?','Publishing every comment immediately','Avoiding all sensitive topics permanently','Clear rules and delayed publication of comments',2,'clear rules and a delay before comments appeared が要因。')],
['cover＝含む・負担する','manageable＝対処可能な','selective＝選択的な'])

add('暗黙の前提','推論は本文から一歩だけ。外の常識を足さない',
"The evening language course has plenty of applicants, but several people have asked whether they can bring their children. We don't have the staff or space to provide childcare at the centre. Rather than assume those applicants aren't committed, we could offer some sessions online. That won't solve every difficulty, and not everyone has a quiet room at home. Still, a mixed format might remove one barrier. I'd ask applicants about their circumstances before finalising the timetable and delivery method.",
[q('What does the speaker imply about some applicants?','They may face practical barriers to attending','They lack interest in languages','They all prefer studying alone',0,'bring their children と childcare 不足から、意欲以外の参加障壁を推論できる。'),q('What should happen before the format is finalised?','Every session should be cancelled','Applicants should be asked about their situations','A childcare centre must be built',1,'ask applicants about their circumstances before finalising。')],
"A restaurant now lists smaller portions alongside its standard meals. The owner says customers should not have to choose between ordering more food than they want and ordering only a side dish. Smaller meals cost less, though not half as much, because preparation and service costs remain. Early feedback has come mainly from lunchtime customers, so the owner will wait before drawing conclusions about evening demand. The menu describes portion sizes neutrally, avoiding labels that suggest smaller meals are intended only for a particular age group.",
[q('What can be inferred about the owner’s aim?','To restrict small meals to children','To make every meal half price','To offer portion choices to a broad range of customers',2,'特定の年齢向けとしない表現と、量の選択肢を増やす理由が根拠。'),q('Why are smaller meals not half the price?','Some costs do not fall in proportion to portion size','Customers demanded higher prices','Evening demand is already known',0,'preparation and service costs remain。量が半分でも費用すべてが半分にはならない。')],
['committed＝意欲・責任感のある','barrier＝障壁','portion＝一人前の量'])

add('要約を選ぶ','一部だけ正しい選択肢より、全体を表す選択肢を選ぶ',
"Our customer helpline answers calls more quickly now, which is good. But the average call is shorter too, and some customers say they have to phone again about the same issue. If we only reward speed, staff may feel pressure to end conversations before problems are resolved. I'd keep measuring waiting time, but also track repeat calls and ask whether the customer got a useful answer. The aim should be efficient resolution, not simply moving through the largest possible number of calls.",
[q('Which best summarises the speaker’s message?','Short calls always mean excellent service','Waiting time should never be measured','Service should be judged by resolution as well as speed',2,'efficient resolution, not simply … number が結論。速さの測定自体は続ける。'),q('What could frequent repeat calls indicate?','The original problem was not fully resolved','The helpline is permanently closed','Every customer is satisfied',0,'phone again about the same issue と before problems are resolved が根拠。')],
"A review of a travel guide praises its clear maps and honest descriptions of accommodation. However, the reviewer notes that restaurant information becomes outdated quickly and suggests checking opening times elsewhere. The guide is most useful for understanding the layout and character of a destination before travelling, rather than making every daily decision during a trip. Its value lies in the stable background it provides. Readers who expect a printed book to reflect every recent change may therefore be disappointed, despite the quality of its research.",
[q('Which is the best summary of the review?','The guide is useless because all its maps are wrong','It is valuable for background, with limits on current details','It guarantees fully current restaurant information',1,'stable background は評価し、変わる情報の限界を指摘している。'),q('What should readers verify separately?','The existence of all destinations','The author’s age','Restaurant opening times',2,'checking opening times elsewhere と具体的に助言。')],
['resolve＝解決する','outdated＝古くなった','stable＝変化しにくい・安定した'])

add('対立する意見','誰が何に賛成しているか整理する',
"Some colleagues want the staff newsletter to become shorter, while others say it already leaves out useful detail. I think both groups have a point. People should be able to see the essential updates quickly, but they shouldn't lose access to explanations. What if each item began with two summary sentences, followed by a link to the full information? We'd need someone to maintain those links, of course. I'd try this format for two editions and then ask readers whether it meets both needs.",
[q('What solution does the speaker propose?','Only publish headlines with no further information','Provide short summaries with links to details','Stop producing the newsletter',1,'two summary sentences, followed by a link が折衷案。'),q('What practical requirement does the speaker mention?','Someone must maintain the links','Readers must write every article','All editions must be printed',0,'need someone to maintain those links。')],
"A proposal to extend market hours has divided traders. Food sellers expect more evening customers, whereas some craft sellers worry about paying staff for hours with few sales. The market committee has suggested a voluntary trial on two Fridays. Traders who close at the usual time will not lose their regular spaces. Supporters consider this a low-risk way to test demand; critics argue that an incomplete market may attract fewer visitors and make the results misleading. The committee has not yet decided how to address that concern.",
[q('What is the critics’ concern about the trial design?','All traders are being forced to participate','An incomplete market could distort the results','Regular spaces will automatically be lost',1,'incomplete market … fewer visitors … misleading が批判の論点。'),q('What is already clear about the proposed trial?','It will run every evening permanently','The committee has resolved every concern','Participation would be optional',2,'voluntary trial と usual time に閉めても不利益なし、が根拠。')],
['essential＝不可欠な・主要な','voluntary＝任意の','misleading＝誤解を招く'])

add('第3週チェック','主張・根拠・限界を分けて解く',
"The survey suggests that customers like the new self-service machines, but remember who answered it: people who had successfully used a machine and then completed the screen survey. We heard very little from those who gave up and went to the staffed counter. Before removing any counters, we should talk to that group as well. I'm not arguing against the machines. I just don't want a decision about everyone's access to be based only on the experiences of people who already find the technology easy.",
[q('What is the main weakness of the survey?','It mainly reflects successful users’ experiences','It contains too many counter users','It proves the machines never work',0,'successfully used … very little from those who gave up。回答者に偏りがある。'),q('What is the speaker recommending?','Remove counters immediately','Abandon all machines','Seek views from people who struggled',2,'talk to that group は gave up の人たち。機械への全面反対ではない。')],
"A housing association offered residents free energy advice. Those who attended later reported lower bills, but attendance was voluntary and participants may already have been motivated to save energy. Furthermore, the winter was warmer than the previous year. The association considers the programme worth continuing because residents valued the advice. However, it will not claim a precise financial saving without stronger evidence. In the next phase, it plans to compare similar households over the same period and record which recommended changes they actually make.",
[q('Why is a precise saving difficult to claim?','No residents attended','Motivation and weather may also explain lower bills','Energy advice always increases bills',1,'voluntary / motivated と warmer winter が他の説明。'),q('Why continue the programme?','Residents found the advice useful','The exact saving has been proved','Every household made identical changes',0,'residents valued the advice が継続理由。金銭効果が確定したためではない。')],
['reflect＝反映する','motivated＝意欲がある','precise＝正確な'])

add('複数の条件を統合','条件を一つずつ満たすか確認する',
"The travel grant is available to staff presenting at a conference, not just attending one. It covers economy travel and up to two nights in a hotel, but meals are excluded. Applications must be approved before tickets are purchased. If the conference is cancelled, contact finance before accepting a travel voucher, because a cash refund may be required under the grant rules. A presentation invitation alone doesn't guarantee funding; the committee also considers how relevant the event is to your current work.",
[q('Which statement about eligibility is correct?','All attendees automatically qualify','Presenters may apply, but approval is not guaranteed','Buying a ticket guarantees funding',1,'presenting が対象。ただし invitation alone doesn’t guarantee funding。'),q('What must happen before tickets are bought?','The application must be approved','A hotel must cancel the booking','Meals must be reimbursed',0,'approved before tickets are purchased。')],
"A retailer accepts returns within thirty days if items are unused and proof of purchase is supplied. Reduced-price goods follow the same rule, except items clearly marked as final sale. Customers who bought online may return items by post or at a branch. Postal costs are refunded only when the retailer sent the wrong item or the product was faulty. A change of mind is an acceptable reason to return an eligible item, but it does not qualify the customer for reimbursement of return postage.",
[q('An unused sale item is not marked “final sale”. With a receipt, may it be returned after twenty days?','No, discounted goods are never returnable','Only if it is faulty','Yes, it meets the stated conditions',2,'30日以内・未使用・購入証明あり。通常の値下げ品にも同じ規則。'),q('Who pays return postage after a simple change of mind?','The customer','The retailer in every case','The nearest branch',0,'郵送料返金は誤配送・不良だけ。返品可能であることと送料負担は別。')],
['eligible＝条件を満たす','proof of purchase＝購入証明','reimbursement＝払い戻し'])

add('控えめな主張','may / likely / not necessarily の強さを読む',
"The early results are promising, but we should be careful about saying the new training causes better performance. Staff who volunteered may have been more interested in the topic to begin with. Also, the improvement was measured immediately after the course, so we don't know whether it will last. I'd describe the training as potentially useful and schedule another assessment in three months. That isn't a reason to stop offering it. It's a reason to match our claims to the evidence we actually have.",
[q('Which description best matches the speaker’s view?','The training is guaranteed to work permanently','The training is useless','The training may help, but more evidence is needed',2,'potentially useful と another assessment。可能性を認め、断定を避ける。'),q('Why assess again in three months?','To see whether the improvement persists','To select only interested volunteers','To avoid measuring performance',0,'don’t know whether it will last に対応する確認。')],
"A report suggests that shared workspaces may help independent workers feel less isolated. It does not imply that every worker will benefit equally. Some respondents valued casual conversation, while others found the same environment distracting. The authors recommend that workspace providers offer both social areas and quiet rooms, where possible. They also note that their survey covered urban locations only. Similar findings should not automatically be assumed for rural areas, where travel distances and the availability of alternatives may shape people's experiences differently.",
[q('Which claim is supported?','Shared spaces eliminate isolation for everyone','Benefits can vary between workers','Rural workers were the main survey group',1,'does not imply … equally と対照的な回答が根拠。'),q('Why do the authors mention urban locations?','To state a limit on applying the findings elsewhere','To prohibit rural shared spaces','To claim travel never matters',0,'urban locations only。調査対象外への一般化を制限している。')],
['potentially＝可能性として','persist＝持続する','imply＝示唆する'])

add('情報の訂正を連続で追う','日付・対象・変更なしの情報を分ける',
"An update on the building inspection: it will still take place on Monday, but inspectors will arrive at ten rather than eight. We originally asked everyone to work from home all day. That's no longer necessary; only the second floor will be closed, and only until lunchtime. Colleagues based there can use the ground-floor meeting rooms, although those rooms won't be available for normal bookings. If you need a quiet space for a client call, reserve a booth on the first floor instead.",
[q('What is the final plan for the second floor?','It will close for the whole week','It will be closed until lunchtime on Monday','It will open at eight for inspections',1,'only the second floor … only until lunchtime。Monday は変わらない。'),q('Where should someone reserve a quiet client-call space?','In a first-floor booth','In a second-floor office','In a normally booked ground-floor meeting room',0,'reserve a booth on the first floor instead が案内。')],
"The organisers have revised the entry arrangements for Sunday's fun run. Registration will now close at eight forty-five, fifteen minutes earlier than advertised, but the race will still start at nine thirty. Participants who collected their numbers in advance can go directly to the starting area. Everyone else must visit the registration desk first. Bags may be left in the supervised tent, though valuables remain the owner's responsibility. The change is intended to reduce queues; it does not shorten the time allocated for the race itself.",
[q('What has changed?','The race starts fifteen minutes earlier','All participants must collect new numbers','The registration deadline is earlier',2,'registration が早まり、start は still nine thirty。'),q('Who can skip the registration desk?','Anyone arriving after nine','Participants who already collected their numbers','Only people without bags',1,'collected their numbers in advance → directly to starting area。')],
['rather than＝〜ではなく','in advance＝前もって','allocated＝割り当てられた'])

add('複数情報の照合','案内と返信を合わせて判断する',
"I saw your request for an extension. Normally we need the report by Friday so the finance team can use it on Monday. Since Monday's meeting has now been postponed, Tuesday morning would be acceptable this time. Please still send the completed sales figures on Friday; it's only the commentary that can wait. I appreciate that you've been covering for a colleague, but let me know earlier next time if the deadline looks difficult. We can usually find a solution when there's enough notice.",
[q('What may be submitted on Tuesday morning?','Only the commentary','Both sections without exception','Only the sales figures',0,'it’s only the commentary that can wait。売上数値はFriday。'),q('What does the speaker ask for in future?','Avoid helping colleagues','Stop writing commentary','Give earlier warning about deadline problems',2,'let me know earlier next time が今後の依頼。')],
"Course notice: Participants should read chapters one and two before Saturday's discussion. Bringing a laptop is optional, and printed extracts will be provided. Email from the tutor: Several people have asked about preparation. Please prioritise chapter two if you are short of time; it contains the case study we will discuss. You do not need to finish the exercises at the end of either chapter. We will work through selected exercises together. The session will assume familiarity with the case study, but not specialist knowledge of the topic.",
[q('If time is limited, what should a participant prioritise?','Buying a laptop','Reading chapter two','Completing every exercise',1,'tutor が prioritise chapter two と補足。'),q('What is expected before the session?','Familiarity with the case study','Specialist knowledge','Completion of all chapter exercises',0,'assume familiarity … but not specialist knowledge。')],
['extension＝期限延長','commentary＝説明・考察部分','familiarity＝内容を知っていること'])

add('反例と限界','一つの成功例で「すべて」を判断しない',
"The four-day-week trial worked well in our design team, but we shouldn't assume the same arrangement will suit customer support. Designers can often move tasks between days, whereas the support line must remain open throughout the week. That doesn't rule out shorter weeks for support staff; it may mean rotating days off instead of closing on Fridays. Before making a company-wide announcement, I'd ask each team to propose a workable schedule and explain how service levels would be maintained. The principle might transfer even if the exact timetable doesn't.",
[q('What is the speaker’s main point?','Support staff can never work shorter weeks','A successful approach may need adapting for other teams','Every team should close on Friday',1,'principle might transfer even if exact timetable doesn’t。実施方法の調整が必要。'),q('What should teams explain before an announcement?','How they would maintain service','Why all trials should stop','How to eliminate all customer calls',0,'explain how service levels would be maintained。')],
"An article describes a village shop that survived by adding a parcel collection service. The extra visits brought some new grocery sales, but the owner stresses that success depended on having spare storage space and enough staff to handle parcels. The article presents the case as an option worth examining, not a universal solution for struggling shops. In places where rent is high or deliveries are already well served, the costs may outweigh the benefits. Readers are encouraged to assess local conditions before copying the model.",
[q('How should readers treat the example?','As proof every shop will benefit','As a reason to stop grocery sales','As an option dependent on local conditions',2,'not a universal solution と assess local conditions が根拠。'),q('What contributed to the shop’s success?','Free rent in every village','Available storage and staffing','The absence of all delivery services',1,'spare storage space and enough staff と明記。')],
['whereas＝一方で','workable＝実行可能な','outweigh＝〜を上回る'])

add('筆者の立場と引用','紹介している意見と本人の意見を混同しない',
"The supplier says the premium plan is essential because it includes unlimited technical support. That may be attractive to a large organisation, but our team rarely needs help outside the initial setup. I'd rather pay for occasional support than commit to a higher monthly fee. Of course, if our needs change, we can reconsider. For now, let's calculate the cost using last year's actual support requests. The supplier's recommendation reflects one possible pattern of use, but it doesn't necessarily reflect ours.",
[q('Which plan does the speaker currently favour?','The premium plan regardless of use','A lower-fee option with occasional paid support','No technical support under any circumstances',1,'pay for occasional support rather than higher monthly fee。supplier の意見と区別。'),q('What evidence does the speaker want to use?','Last year’s actual support requests','The supplier’s largest customer’s spending','An assumption of unlimited problems',0,'using last year’s actual support requests が費用算定の根拠。')],
"Some commentators claim that working from home inevitably weakens team relationships. The writer of this article considers that conclusion too broad. She argues that relationships depend partly on how teams communicate, not simply on where people sit. Regular opportunities to exchange ideas may matter more than physical presence alone. She nevertheless acknowledges that new employees can find remote work especially challenging and may need additional support. Her argument is not that location is irrelevant, but that it cannot by itself explain the quality of teamwork.",
[q('What is the writer’s position?','Location alone does not determine team relationships','Remote work inevitably destroys teamwork','New employees never need support',0,'cannot by itself explain … teamwork が立場。冒頭の claim は他者の意見。'),q('Why mention new employees?','To withdraw the entire argument','To prove communication has no role','To acknowledge a particular challenge',2,'nevertheless acknowledges は自分の主張に留保を加える役割。')],
['commit to＝継続的に約束する','inevitably＝必然的に','acknowledge＝認める'])

add('第4週チェック','時間内に主旨と根拠を取る',
"We're considering removing the printed instruction sheet from our product boxes and using a link instead. It would reduce paper and let us update the guidance quickly. However, we receive calls from customers who struggle to connect the device before they can access online help. I'd keep a brief setup card in the box and put the detailed instructions online. We should test whether customers can complete the first steps using that card alone. Saving paper is worthwhile, but support needs to be available at the point people actually need it.",
[q('What compromise does the speaker suggest?','Remove all instructions','Keep a short setup card and move details online','Print every update in full',1,'brief setup card in the box と detailed instructions online の組合せ。'),q('What should the test establish?','Whether the card alone enables the initial setup','Whether every customer prefers paper','Whether online guidance can never change',0,'complete the first steps using that card alone が検証点。')],
"The city trialled a free shuttle between the station and a business park. Passenger numbers were modest overall, but the earliest service was often full. A consultant warned that daily averages concealed this difference. She recommended adjusting the timetable to match demand before judging the service unsuccessful. The council will add one early journey and reduce an afternoon service during a further six-week trial. It will also ask passengers what alternatives they would use, to understand whether the shuttle mainly replaces car journeys or other public transport.",
[q('Why might the daily average be misleading?','It hides strong demand at a particular time','It proves every service was full','It includes no passenger counts',0,'earliest service … full だが averages concealed this difference。'),q('Why ask about passengers’ alternatives?','To stop the earliest service','To determine what travel the shuttle replaces','To guarantee the trial becomes permanent',1,'whether … replaces car journeys or other public transport が目的。')],
['setup＝初期設定','conceal＝隠す','alternative＝代替手段'])

add('総合練習 A','初回は音声1回・辞書なし。最後に根拠を確認する',
"The online induction has reduced the time managers spend repeating basic information, but new staff say they miss the chance to ask small questions informally. I don't think returning to a full day of presentations is the answer. We could keep the online modules and add a short conversation with a colleague during the first week. That person wouldn't replace the manager or assess performance; they'd simply explain everyday practices. Let's try it with the next group of recruits and ask which questions still go unanswered before deciding whether to expand it.",
[q('What change is proposed?','Replace all modules with presentations','Add an informal colleague conversation','Use colleagues to grade new staff',1,'keep … modules and add … conversation。既存の効率性を保ち補完する。'),q('What would the colleague mainly do?','Assess performance formally','Repeat every module in full','Explain day-to-day practices',2,'simply explain everyday practices と役割を限定している。')],
"A study group replaced weekly chapter summaries with questions written by members. The organiser hoped this would encourage closer reading. Discussions became livelier, yet a few members said they felt less confident without a summary to check their understanding. Rather than abandon the new approach, the group agreed to share a brief outline after each discussion. This preserves the incentive to read independently while providing a reference afterwards. The organiser will review participation next month, recognising that lively discussion does not necessarily mean every member is benefiting equally.",
[q('Why share the outline after the discussion?','To prevent anyone reading beforehand','To combine independent preparation with later support','To replace member questions entirely',1,'independently と reference afterwards の両立。'),q('What limitation does the organiser recognise?','More active discussion may not benefit everyone equally','The outline guarantees full understanding','No members enjoyed the new method',0,'最後の does not necessarily … equally が限界。')],
['induction＝導入研修','recruit＝新しいメンバー','incentive＝動機づけとなるもの'])

add('総合練習 B・1ヶ月の振り返り','初回は音声1回・辞書なし。Day 29と合わせて確認する',
"The town's tool-lending service is popular, but the waiting list is growing for a few items, especially drills. Buying more of everything would be expensive and might leave less-used tools sitting on shelves. I'd first shorten the loan period for the busiest items, provided members can request an extension when no one is waiting. We should also record unsuccessful requests, since completed loans alone don't show unmet demand. After a month, we'll be better placed to decide which extra tools are worth buying and whether the shorter loans create difficulties.",
[q('What is the proposed first step?','Buy more of every tool','Close the service to new members','Shorten loans for the most popular tools, with conditional extensions',2,'first shorten … busiest items、延長は no one is waiting が条件。'),q('Why record unsuccessful requests?','To identify demand not shown by completed loans','To discourage members from borrowing','To prove unused tools are popular',0,'completed loans alone don’t show unmet demand。成立しなかった需要も測るため。')],
"A publisher tested audio versions of its long articles. Subscribers who tried them spent more time with the publication, but most trial users were already its most engaged readers. The editor therefore hesitates to claim that audio will attract a new audience. She plans to offer a selection to non-subscribers and ask what they would otherwise have listened to. Meanwhile, audio production will focus on articles whose arguments benefit from sustained attention. The aim is to test both the audience opportunity and the editorial value, rather than convert every article simply because the technology makes it possible.",
[q('Why is the editor cautious about attracting a new audience?','No subscribers used the audio','Trial users were already highly engaged','All articles had already been converted',1,'most trial users were already … most engaged readers。新規層での効果は未確認。'),q('Which best describes the next stage?','Convert everything immediately','Stop audio because technology is unavailable','Test new audiences and choose articles suited to audio',2,'non-subscribers と articles … sustained attention の二本立て。')],
['unmet demand＝満たされていない需要','engaged＝熱心に関わっている','sustained attention＝持続的な注意'])

if __name__ == '__main__':
    import random
    rng=random.Random(963)
    positions=[0,1,2]*40
    rng.shuffle(positions)
    for d in D:
        for kind in ('listening','reading'):
            for question in d[kind]['questions']:
                correct=question['options'][question['answer']]
                others=[o for i,o in enumerate(question['options']) if i!=question['answer']]
                rng.shuffle(others)
                new_position=positions.pop()
                others.insert(new_position,correct)
                question['options']=others
                question['answer']=new_position
    p=Path(__file__).parent
    assert len(D)==30
    for d in D:
        for kind in ('listening','reading'):
            assert len(d[kind]['questions'])==2
            for question in d[kind]['questions']:
                assert len(question['options'])==3 and 0<=question['answer']<3
        (p/'scripts'/f'day{d["day"]:02d}.txt').write_text(d['listening']['text'])
    (p/'content.json').write_text(json.dumps(D,ensure_ascii=False,indent=2))
    print(f'{len(D)} days, {sum(len(d[k]["questions"]) for d in D for k in ("listening","reading"))} questions')
