import json
from pathlib import Path

P = Path(__file__).resolve().parent

def q(prompt, a, b, c, answer, why):
    return {"prompt": prompt, "options": [a, b, c], "answer": answer, "why": why}

# Each entry adds a second paragraph and two questions to the original passage.
# The first two questions in content.json remain, giving four questions per day.
E = [
    ("The library has arranged for one staff member to supervise the building from nine. That employee can issue loans but cannot answer specialist research questions. Students have welcomed the change, while some residents have asked why Saturday hours are not included. The library says it wants to measure weekday demand first, because extending the trial would require additional staffing funds.",
     q("Why are Saturday hours not changing during the trial?", "Weekend demand has already been measured", "The library wants weekday evidence before spending more", "Students opposed Saturday opening", 1, "weekday demandを先に測り、追加の人件費を判断するとある。週末需要を測定済みとは書かれていない。"),
     q("What can the supervising employee do before ten?", "Lend books", "Answer specialist research questions", "Change the weekend schedule", 0, "can issue loans とある。一方、専門的な調査質問には答えられない。")),
    ("After six weeks, staff said they finished complex reports with fewer interruptions. However, response times to internal messages became slightly longer, so urgent requests are now marked with a special label. Managers will compare project quality and staff feedback after three months. They say the rule will continue only if focused work improves without creating serious delays for colleagues.",
     q("What problem appeared after quiet hour was introduced?", "Customers could no longer call support", "Internal messages sometimes received slower replies", "Employees stopped writing reports", 1, "response times to internal messages became slightly longer が問題。顧客対応は通常どおり。"),
     q("What will determine whether the rule continues?", "Only the number of messages sent", "Whether every team uses the same hour", "A balance between better focus and acceptable delays", 2, "集中作業の改善と、同僚への深刻な遅延がないことの両方を条件にしている。")),
    ("On busy days, timed entry may still be introduced temporarily to prevent overcrowding. This would apply to the building, not just the workshops, and would be announced on the website that morning. The photography policy may also vary for borrowed exhibitions because some lenders protect image rights. Signs beside each gallery entrance show any additional restrictions, so visitors should not assume that one rule applies everywhere.",
     q("When might visitors need a timed entry slot?", "Every time they attend a workshop", "When the building is expected to be overcrowded", "Whenever they bring a large bag", 1, "busy days に overcrowding を防ぐため一時導入される可能性がある。常時ではない。"),
     q("Why might photography rules differ between galleries?", "Some works belong to lenders with different conditions", "Flash is required in borrowed exhibitions", "The lockers are inside the galleries", 0, "borrowed exhibitionsでは貸し手が画像権利を保護する場合があるため。")),
    ("The change has required more flexible communication. Instead of assigning people several weeks ahead, the coordinator sends a message on Thursday based on the forecast. Volunteers who cannot attend are not penalised, although the system works only if enough people respond. Early figures show lower water use, but the coordinator says plant health over the whole season matters more than a single month's savings.",
     q("What new difficulty does the system create?", "Volunteers receive less advance notice", "Plants are never inspected", "Weather forecasts are no longer used", 0, "木曜に予報を基に連絡するため、数週間前の固定予定より通知が遅くなる。"),
     q("What does the coordinator consider the better measure of success?", "One month of low water use", "Plant health across the season", "The number of Saturday visits", 1, "single month's savings より plant health over the whole season が重要と述べる。")),
    ("Borrowers must also take reasonable steps to protect equipment in transit. The company provides padded cases, but it will not pay for damage caused by leaving a laptop unattended in a vehicle. Normal technical faults should be reported through the usual help desk and do not automatically make the borrower responsible. Managers will review the scheme if weekend loans begin to reduce the supply of devices needed for Monday work.",
     q("When might a borrower be held responsible for damage?", "When a normal technical fault occurs", "When the laptop is left unattended in a vehicle", "Whenever a padded case is used", 1, "車内に放置して生じた損傷は会社が負担しない。通常の技術的不具合とは区別される。"),
     q("Why might managers reconsider the scheme?", "Weekend loans could leave too few laptops for work", "Employees have stopped studying", "The IT team wants paid outside work", 0, "Monday work に必要な端末の供給を減らす場合は見直すとある。")),
    ("The hotel manager replied that the phrase had been based on the distance shown on a map, not on a walk with luggage. She agreed that this was not a useful measure for arriving guests. The website will now state both the distance and a typical walking time, and reception staff will send taxi information with booking confirmations. The hill itself cannot be changed, but expectations can be.",
     q("Why had the hotel called it a short walk?", "Staff had timed guests carrying bags", "It relied on map distance", "The station recently moved", 1, "map上の距離を基準にしていた。荷物を持った実測ではない。"),
     q("What broader lesson does the final sentence express?", "Hotels should remove all hills", "Accurate information can help guests plan", "Every guest should walk from the station", 1, "地形は変えられなくても、正確な情報で期待と計画は調整できるという意味。")),
    ("A local employers' group has offered to promote the remaining evenings, but the director does not want free publicity to distort the results. Instead, the museum will use the same advertising budget each month and vary only one feature, such as the tour schedule. This should make comparisons more meaningful, although seasonal events in the town may still influence attendance.",
     q("Why will the museum keep its advertising budget the same?", "To make monthly comparisons fairer", "To prevent all employers from attending", "Because tours have been cancelled", 0, "宣伝条件を一定にして、変える要素を一つに絞り比較しやすくするため。"),
     q("What limitation may still affect the comparison?", "The museum has no evening staff", "Seasonal events may change attendance", "Visitors cannot join tours", 1, "townの季節イベントが来館者数に影響し得ると明記される。")),
    ("Both providers offer a one-week sample lesson. The reviewer recommends using it to test not only the teaching style but also whether study time fits naturally into a normal week. Completion statistics appear higher for Course B, yet its learners may have had more free time from the beginning. The figures therefore support asking further questions rather than declaring one format superior.",
     q("What should learners test during the sample week?", "Only the camera price", "Teaching style and practical fit with their schedule", "Whether Course B has more lessons", 1, "teaching styleに加え、通常週に学習時間が自然に収まるかを試す。"),
     q("Why should the completion figures be treated cautiously?", "The courses teach different subjects", "Course A published no lessons", "The groups may have differed before starting", 2, "Course Bの学習者は元から余暇が多かった可能性があり、単純比較できない。")),
    ("Delivery companies have also asked for space near the shops, so the proposed bays would serve more than one purpose. That could make them busy at exactly the times customers need them. The council is considering thirty-minute limits and monitoring during the first month. Shop owners say enforcement matters: a loading bay that is permanently occupied would solve little, even if it looks suitable on a plan.",
     q("What possible conflict concerns the shop owners?", "Delivery vehicles and customers may need the bays at the same time", "Cyclists want to use the shops as parking", "The council plans to remove every loading bay", 0, "配送業者と重い商品を受け取る顧客の利用時間が重なる可能性。"),
     q("What does the last sentence imply?", "A design works only if its rules operate in practice", "Plans are always more reliable than trials", "Monitoring would make bays unnecessary", 0, "図面上適切でも常時占有されれば役立たないため、運用と取締りが必要。")),
    ("Demand is greatest for guitars, and several are already reserved for the next term. The school is considering shorter first loans for popular instruments, but teachers warn that beginners need enough time to build a routine. They suggest offering group practice rooms instead. This would let students without quiet space at home practise regularly without reducing the length of their loan.",
     q("Why are teachers cautious about shorter loans?", "Beginners need time to establish regular practice", "Guitars cannot be repaired", "Practice rooms are already full", 0, "初心者が習慣を作るのに十分な時間が必要だから。"),
     q("What problem would group practice rooms address?", "A lack of suitable practice space at home", "The cost of donating instruments", "Waiting for repair checks", 0, "自宅に静かな場所がない生徒も定期的に練習できる。")),
    ("To improve the next survey, researchers will invite employees at random rather than relying only on volunteers. They will record how often participants visit the garden and compare stress levels over time. Even this design cannot remove every difference between people, but it can reduce the risk of confusing interest in the garden with its effects. Management has promised to publish negative as well as positive results.",
     q("Why will employees be invited at random?", "To reduce volunteer-related bias", "To guarantee that stress disappears", "To close the garden to interested staff", 0, "希望者だけでは元々の関心などが結果に混ざるため、random invitationで偏りを減らす。"),
     q("What does management's promise support?", "Selective reporting of good news", "Transparent reporting of the findings", "Immediate proof of causation", 1, "negative resultsもpositive resultsも公表するため透明性を高める。")),
    ("If the workshop goes ahead, students will receive preparatory material on Monday. The fee covers teaching and lunch but not travel. Students who withdraw after confirming payment may receive a refund only if their place can be filled. The organiser advises applicants not to make non-refundable travel arrangements until they receive the final confirmation email.",
     q("What is NOT included in the workshop fee?", "Lunch", "Teaching", "Travel", 2, "fee covers teaching and lunch but not travel と明記される。"),
     q("Why should students wait before booking non-refundable travel?", "The workshop may not reach the minimum registration", "The venue has no wheelchair access", "Final projects have been cancelled", 0, "12人に達しなければ実施されないため、最終確認前の返金不可予約を避ける。")),
    ("The smaller range has also changed staff training. Previously, new cooks learned many recipes but prepared each one only occasionally. They now repeat the same dishes often enough to notice small errors and improve timing. The owner accepts that a shorter menu may disappoint customers seeking variety; she hopes seasonal specials can offer some change without returning to the complexity of twenty permanent dishes.",
     q("How has the shorter menu affected training?", "Cooks repeat dishes and refine their performance", "New cooks no longer learn recipes", "Timing has become impossible to measure", 0, "同じ料理を繰り返し、小さな誤りや時間配分を改善できる。"),
     q("What compromise may provide variety?", "Restoring all twenty dishes permanently", "Adding occasional seasonal specials", "Changing the menu every day", 1, "seasonal specialsで変化を出しつつ、常設20品の複雑さには戻らない案。")),
    ("In the repeated trial, participants will be assigned to groups rather than choosing an incentive. Researchers will also record cancelled visits, since booking a session is not the same as attending it. The centre hopes to learn whether reminders help people remember existing intentions, while discounts persuade them to form new habits. Those are related outcomes, but they are not identical.",
     q("Why will participants be assigned to groups?", "To make the groups more comparable", "To ensure everyone receives a discount", "To prevent attendance from being recorded", 0, "自分で選ばせず割り当てることで、開始時点の差を小さくして比較する。"),
     q("What distinction does the centre want to examine?", "Remembering plans versus developing new habits", "Booking online versus paying cash", "Weekly messages versus monthly reports", 0, "remindersは既存の意図を思い出させ、discountsは新習慣を促す可能性という区別。")),
    ("Accessibility groups support the choice but have asked the theatre to explain the paper option more clearly. If customers discover it only after struggling online, the option is less useful. The theatre will add the information beside the ticket selector and train telephone staff to mention it. It will measure digital use, customer complaints, and total energy consumption rather than presenting one figure as a complete account of sustainability.",
     q("Why must the paper option be explained earlier?", "An unknown option cannot effectively improve access", "Printed tickets use no resources", "Telephone bookings are ending", 0, "困った後に初めて知るのでは利用しにくく、access改善になりにくい。"),
     q("How will the theatre assess sustainability?", "By counting paper tickets only", "Using several environmental and customer measures", "By ignoring energy consumption", 1, "digital use、complaints、energy consumptionを合わせて見る。")),
    ("During the first fortnight, the bench near the crossing was used frequently, especially in the afternoon. The shop-side bench was used less often but caused two delivery complaints. The group has moved it ten metres away and will continue observing. It cautions that low use does not necessarily mean a bench is unnecessary: rain, temporary roadworks, and poor signage may also influence the figures.",
     q("What happened to the shop-side bench?", "It was made permanent", "It was moved after delivery complaints", "It became the most popular bench", 1, "delivery complaintsを受けて10メートル移動した。"),
     q("Why does the group hesitate to interpret low use directly?", "Several temporary factors may affect use", "Observation has already ended", "Every bench must remain in its first position", 0, "雨、道路工事、標識など別要因でも利用数が下がり得る。")),
    ("The trial also revealed that readers behaved differently across subjects. Comments on practical articles often added useful examples, whereas political pieces attracted repeated arguments between a small number of users. The editor plans to publish monthly moderation figures and invite reporters to recommend articles where discussion could add evidence. Selection will therefore depend on likely public value as well as staff capacity.",
     q("Which articles produced particularly useful comments?", "Practical articles", "All political articles", "Articles without readers", 0, "practical articlesではuseful examplesが追加された。"),
     q("What two factors will guide the selection of articles?", "Length and publication date", "Public value and moderation capacity", "Advertising income and author age", 1, "likely public value と staff capacity の両方で判断する。")),
    ("Sales of smaller portions were strongest among office workers who wanted a light lunch, but families also ordered them for children. This supports the decision to avoid age-based labels. Some diners asked whether two small plates could be combined at a discount. The owner declined for now, explaining that the purpose is to offer flexible quantities, not to create a cheaper route to the same amount of food.",
     q("What supports the neutral menu labels?", "Different kinds of customers order smaller portions", "Only older diners buy them", "Every portion costs exactly half", 0, "会社員と家族の子どもなど複数層が注文し、特定年齢向けではない。"),
     q("Why did the owner reject the combined discount?", "Small plates cannot be served together", "It would undermine the portion policy's purpose", "Families complained about flexibility", 1, "量の柔軟性が目的で、同量を安く買う制度にする意図ではない。")),
    ("The guide includes a companion website where the publisher posts corrections submitted by readers. The reviewer found it helpful but noticed that rural businesses were updated less often than city ones. She recommends treating silence as a lack of new information, not proof that nothing has changed. Used together, the book and website offer orientation and updates, but travellers still need to confirm details that matter to their plans.",
     q("What weakness did the reviewer find in the website?", "It contains no reader corrections", "Rural information is updated less consistently", "It replaces the guide's maps", 1, "rural businessesはcity onesより更新頻度が低い。"),
     q("What does the reviewer advise travellers to do?", "Assume unchanged entries are accurate", "Confirm important practical details", "Use only the printed book", 1, "予定に重要な情報はなお確認する必要がある。更新なしは変化なしの証明ではない。")),
    ("To improve the trial, the committee may ask all traders to record hourly sales whether or not they stay open late. That would show whether evening sales are additional or simply shifted from earlier hours. It is also considering shared security costs, because small traders say paying individually would make participation unrealistic. A final decision will be made only after traders see the full trial conditions.",
     q("Why record hourly sales?", "To see whether evening business is genuinely additional", "To force every trader to stay late", "To remove regular market spaces", 0, "夕方の売上が追加需要か、昼から移っただけかを確認する。"),
     q("What could make the trial more practical for small traders?", "Individual security contracts", "Shared security costs", "Permanent compulsory hours", 1, "security費を共同負担する案が参加現実性を高める。")),
    ("The new comparison will include homes of similar size and heating type, but researchers recognise that behaviour remains hard to match exactly. They will therefore report a range of outcomes rather than one promised saving. Residents will also receive follow-up calls to identify recommendations that were difficult to apply. Advice that looks effective on paper has limited value if households cannot act on it.",
     q("Why will the association report a range?", "Household behaviour cannot be perfectly matched", "All homes use identical heating", "It has promised one exact saving", 0, "住宅条件をそろえても行動差は完全にはそろわないため、単一額でなく幅を示す。"),
     q("What will follow-up calls help identify?", "Advice residents could not easily put into practice", "Residents who want warmer winters", "The price of the original survey", 0, "recommendations that were difficult to apply を把握する。")),
    ("Gift receipts count as proof of purchase, although any refund goes to the original payment method. Hygiene-sensitive products cannot be returned once their seal is broken unless they are faulty. These limits are displayed at checkout and online. The retailer advises customers to inspect deliveries promptly, because reporting a fault after extensive use may make it harder to establish whether the problem existed on arrival.",
     q("Where is a refund for a gift purchase sent?", "To the person holding the gift receipt", "To the original payment method", "Only as cash at a branch", 1, "gift receiptは購入証明になるが、refundはoriginal payment methodへ戻る。"),
     q("When may an opened hygiene-sensitive product be returned?", "Whenever the customer changes their mind", "Only after thirty days", "If it is faulty", 2, "seal開封後は原則不可だが、faultyの場合は例外。")),
    ("The authors are now planning interviews to explore why some users feel distracted. Noise may be one factor, but interruptions, lack of privacy, and the type of work could also matter. They will include smaller towns in the next stage, while avoiding claims that one additional group represents every rural setting. The aim is to explain variation, not merely produce a larger average.",
     q("What is the purpose of the planned interviews?", "To explore reasons for different experiences", "To prove noise is the only cause", "To exclude people in small towns", 0, "distractedになる理由をnoise以外も含めて調べ、variationを説明する。"),
     q("Why will the authors still be cautious about rural claims?", "One added group cannot represent all rural settings", "Urban results have been withdrawn", "Rural workers never use shared spaces", 0, "一つの追加集団だけで全農村環境を代表できないと明記。")),
    ("Because some runners travel by an early bus that arrives at eight fifty, the organisers will keep a separate desk open for those who warned them in advance. This is an exception, not a second general deadline. Late arrivals without prior notice may be unable to take part because safety staff must finalise the participant list. The organisers have updated the website and emailed registered runners.",
     q("Who may use the separate registration desk?", "Any runner arriving after nine", "Pre-notified runners on the early bus", "Participants who collected numbers in advance", 1, "early bus利用を事前連絡した人への限定例外。一般的な第二締切ではない。"),
     q("Why might an unannounced late runner be refused?", "The participant list must be finalised for safety", "The race now starts at eight forty-five", "The bag tent has been removed", 0, "安全担当が参加者リストを確定する必要があるため。")),
    ("The tutor later clarified that students should note one question about the case study rather than prepare a formal presentation. During the session, small groups will compare their questions before the tutor introduces a framework for analysis. The printed extracts contain the case study but not the background chapter, so anyone relying on paper should arrive early enough to collect the material and skim the missing context.",
     q("What should students prepare about the case study?", "One question", "A formal presentation", "A specialist report", 0, "one questionをメモする。formal presentationは不要。"),
     q("What is missing from the printed extracts?", "The case study", "The background chapter", "All selected exercises", 1, "extractsにはcase studyはあるがbackground chapterはない。")),
    ("A neighbouring shop tried the same service but abandoned it within three months. Its sales rose slightly, yet parcel queues blocked access to the counter and regular customers complained. This contrasting case strengthens the article's central warning. A service can create more visits while still harming the main business if layout and staffing are unsuitable. Revenue figures alone therefore cannot show whether the model works.",
     q("Why did the neighbouring shop stop the service?", "It attracted no parcel users", "Queues disrupted its main business", "Its storage space increased", 1, "parcel queuesがcounterへのアクセスを塞ぎ、通常客が不満を持った。"),
     q("What does the contrasting case demonstrate?", "More visits do not always mean overall success", "Revenue is the only useful measure", "Every village shop needs fewer staff", 0, "来店増でも本業を害すれば成功とは限らない。")),
    ("The writer cites a software team that meets in person twice a month and communicates effectively between meetings. She also describes a fully office-based team whose members rarely share unfinished ideas. These examples are not offered as proof that remote work is better. Their purpose is to show why location and relationship quality should be measured separately before conclusions are drawn.",
     q("Why does the writer compare the two teams?", "To prove remote work is always superior", "To separate location from communication quality", "To recommend ending all office work", 1, "場所と関係・communicationの質を別々に測る必要を示す例。"),
     q("What does 'These examples' refer to?", "The two teams with different work arrangements", "Only new employees", "Additional support programmes", 0, "直前のsoftware teamとoffice-based teamの二例を指す。")),
    ("The extra early journey will be timed to meet the first train from the city. During the next trial, automatic counters will record passengers at every stop rather than only at the business park. This may reveal whether local residents use the shuttle for shorter trips. The consultant says success criteria should be agreed before results are seen, so that the council does not select whichever measure makes its preferred decision look strongest.",
     q("What might the stop-by-stop counters reveal?", "Whether people make shorter local journeys", "Why the first train was cancelled", "Which drivers prefer cars", 0, "全停留所で数えることでbusiness parkまで行かない短距離利用も分かる。"),
     q("Why set success criteria in advance?", "To avoid choosing a convenient measure after seeing results", "To guarantee the shuttle continues", "To reduce the number of passengers", 0, "結果後に都合のよい尺度だけ選ぶことを防ぐ。")),
    ("The outline will list the chapter's argument and key terms but will not answer the members' questions directly. Members can revise their own responses after reading it. The organiser will assess participation through a short anonymous survey as well as attendance figures, because quiet members may prepare carefully without speaking often. This method also recognises that confidence and understanding are related but distinct outcomes.",
     q("What will the outline deliberately avoid doing?", "Listing key terms", "Giving direct answers to member questions", "Summarising the chapter's argument", 1, "argumentとkey termsは載せるが、questionsへのdirect answersは載せない。"),
     q("Why use an anonymous survey as well as attendance?", "Attendance alone misses some forms of engagement", "Quiet members never prepare", "The organiser wants fewer responses", 0, "発言が少なくても準備する人がおり、出席・発言だけでは参加を捉えきれない。")),
    ("Producing audio requires editorial work beyond simply reading the text aloud. References to charts must be rewritten, and headings need spoken transitions so listeners can follow the structure. The publisher will track completion, return visits, and voluntary survey responses, while recognising that each measure captures a different kind of value. A successful experiment may therefore lead to a selective audio programme rather than a complete replacement of written articles.",
     q("Why must some articles be adapted for audio?", "Visual references and structure need verbal explanation", "Listeners cannot understand headings", "Audio removes the need for editing", 0, "chartsへの参照やheadingの構造を音声で分かる形に書き換える必要がある。"),
     q("What outcome does the publisher consider possible?", "Replacing every written article", "A selective continuing audio programme", "Ending all audience research", 1, "成功してもcomplete replacementではなくselective programmeになり得る。")),
]

data = json.loads((P / "content.json").read_text())
assert len(data) == len(E) == 30
for row, (extra, q3, q4) in zip(data, E):
    reading = row["reading"]
    if len(reading["questions"]) == 2:
        reading["text"] = reading["text"].rstrip() + "\n\n" + extra
        reading["questions"].extend([q3, q4])
    assert 130 <= len(reading["text"].split()) <= 230, (row["day"], len(reading["text"].split()))
    assert len(reading["questions"]) == 4, row["day"]
    assert "\n\n" in reading["text"]
    for question in reading["questions"]:
        assert len(question["options"]) == 3
        assert question["answer"] in (0, 1, 2)
        assert question["why"]
(P / "content.json").write_text(json.dumps(data, ensure_ascii=False, indent=2))
print(f"Updated {len(data)} passages; {sum(len(x['reading']['questions']) for x in data)} Reading questions")
